//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTIDataBaseProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildingsTable()
        {
            this.FlatsTable = new HashSet<FlatsTable>();
        }
    
        public string Kadastr { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public int Land { get; set; }
        public int Year { get; set; }
        public string Material { get; set; }
        public string Base { get; set; }
        public string Comments { get; set; }
        public int Wear { get; set; }
        public int Flow { get; set; }
        public int Line { get; set; }
        public int Square { get; set; }
        public byte[] Picture { get; set; }
        public int Flats { get; set; }
        public bool Elevator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlatsTable> FlatsTable { get; set; }
    }
}
